"""Test that all SDK modules and classes can be imported."""

import pytest


def test_import_main_client():
    """Test importing unified Client."""
    from taruvi import Client
    assert Client is not None
    assert callable(Client)


def test_auth_module_via_client():
    """Test that auth module is accessible via client.auth (AuthManager merged into AuthModule)."""
    from taruvi import Client

    client = Client(api_url="http://localhost:8000", app_slug="test-app", mode="sync")

    # Auth module should be accessible
    assert hasattr(client, 'auth')
    assert client.auth is not None

    # Should have authentication methods
    assert hasattr(client.auth, 'signInWithPassword')
    assert hasattr(client.auth, 'signInWithToken')
    assert hasattr(client.auth, 'signOut')
    assert hasattr(client.auth, 'get_current_user')


def test_import_not_authenticated_error():
    """Test importing NotAuthenticatedError exception."""
    from taruvi import NotAuthenticatedError
    from taruvi.exceptions import NotAuthenticatedError as DirectImport
    assert NotAuthenticatedError is not None
    assert NotAuthenticatedError is DirectImport


def test_syncclient_removed():
    """Test that SyncClient is no longer exported (breaking change in v0.2.0)."""
    with pytest.raises(ImportError):
        from taruvi import SyncClient  # noqa: F401


def test_import_all_async_modules():
    """Test importing all async module classes."""
    from taruvi._async.modules.auth import AsyncAuthModule
    from taruvi._async.modules.database import AsyncDatabaseModule, AsyncQueryBuilder
    from taruvi._async.modules.functions import AsyncFunctionsModule
    from taruvi._async.modules.storage import AsyncStorageModule
    from taruvi._async.modules.secrets import AsyncSecretsModule
    from taruvi._async.modules.policy import AsyncPolicyModule
    from taruvi._async.modules.app import AsyncAppModule
    from taruvi._async.modules.settings import AsyncSettingsModule
    from taruvi._async.modules.users import AsyncUsersModule

    assert AsyncAuthModule is not None
    assert AsyncDatabaseModule is not None
    assert AsyncQueryBuilder is not None
    assert AsyncFunctionsModule is not None
    assert AsyncStorageModule is not None
    assert AsyncSecretsModule is not None
    assert AsyncPolicyModule is not None
    assert AsyncAppModule is not None
    assert AsyncSettingsModule is not None
    assert AsyncUsersModule is not None


def test_import_all_sync_modules():
    """Test importing all sync module classes (generated by unasync)."""
    from taruvi._sync.modules.auth import AuthModule
    from taruvi._sync.modules.database import DatabaseModule, QueryBuilder
    from taruvi._sync.modules.functions import FunctionsModule
    from taruvi._sync.modules.storage import StorageModule
    from taruvi._sync.modules.secrets import SecretsModule
    from taruvi._sync.modules.policy import PolicyModule
    from taruvi._sync.modules.app import AppModule
    from taruvi._sync.modules.settings import SettingsModule
    from taruvi._sync.modules.users import UsersModule

    assert AuthModule is not None
    assert DatabaseModule is not None
    assert QueryBuilder is not None
    assert FunctionsModule is not None
    assert StorageModule is not None
    assert SecretsModule is not None
    assert PolicyModule is not None
    assert AppModule is not None
    assert SettingsModule is not None
    assert UsersModule is not None


def test_no_import_errors():
    """Test that importing the package doesn't raise errors."""
    try:
        import taruvi
        assert True
    except ImportError as e:
        pytest.fail(f"Import error: {e}")
